import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>YNAB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://www.youneedabudget.com/">YNAB!</a>
        </h1>
        <p className={styles.description}>
          Get started by editing logging <a href="/dashboard">in</a>.
        </p>
      </main>

      <footer className={styles.footer}>
        <a href="https://cdt.works/" target="_blank" rel="noopener noreferrer">
          <span style={{ marginRight: 2 }}>Powered by </span>
          <Image src="/cdt.png" alt="CDT Logo" width={85} height={25} />
          {/* <span className={styles.logo} style={{ marginLeft: 5 }}>
            CDT Works
          </span> */}
        </a>
      </footer>
    </div>
  );
}
